name: Lint

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: go.sum

    - name: Use latest scheduler0-go-client
      run: |
        go mod edit -dropreplace github.com/scheduler0/scheduler0-go-client
        go get github.com/scheduler0/scheduler0-go-client@latest
        go mod tidy

    # - name: Run golangci-lint
    #   uses: golangci/golangci-lint-action@v6
    #   with:
    #     version: latest
    #     args: --timeout=5m

